# Generated by Django 3.2.14 on 2022-07-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('00', 'Not specified'), ('10', 'Smoke'), ('20', 'Drinks'), ('30', 'Foods'), ('40', 'Perfumes and Cosmetics'), ('50', 'Watches Jewelry & Accessories'), ('60', 'Toys'), ('70', 'Fashion'), ('80', 'Electronics'), ('90', 'Other Goods'), ('91', 'Readings and Publications'), ('92', 'Souvenirs (Local Goods)')], max_length=30)),
            ],
        ),
    ]
