name: CI and CD

on: 
  push:
    branches:
      - master

jobs:
    continuous-integration:
    name: CI and CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: 3.8.10
      
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      
      - name: Run tests
        run: |
            python manage.py test
        