name: CI and CD

on: 
  push:
    branches:
      - master

jobs:
  ci_cd:
    name: CI and CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run tests
        run: python manage.py test
        